### ISSUE TITLE
Ask an maybe naive question.

### ISSUE THREAD

**Issue by whimsycwd** [hamcrest/JavaHamcrest#115]
I have do some google. and Can't find answer.

* The api already define
allOf(Matcher<? super T>... matchers) 

Why would we need below api:
allOf(Matcher<? super T> first, Matcher<? super T> second) 
allOf(Matcher<? super T> first, Matcher<? super T> second, Matcher<? super T> third) 
....
allOf(Matcher<? super T> first, Matcher<? super T> second, Matcher<? super T> third, Matcher<? super T> fourth, Matcher<? super T> fifth, Matcher<? super T> sixth) 

* Why stops at 6 parameters?

Thanks in advanced.

**Comment by npryce** [comment]
Javac 1.6 warns when passing values of a generic type to a varargs
parameter because of a hole in Java's type system. The overloaded methods
do not produce the warning. We stopped at 6 because that seemed enough for
most cases and users can write their own overload of allOf if they need
more parameters.
