### ISSUE TITLE
Matchers as JDK8 Predicates?

### ISSUE THREAD

**Issue by helsing** [hamcrest/JavaHamcrest#148]
Is there anyone other than me, that would love if the next version of JavaHamcrest could make the leap into JDK8 and make matchers to be of type `java.util.function.Predicate`?

This way, matchers could be used anywhere a Predicate is expected and it would be so nice if descriptive messages (including mismatch messages) could be built using functional composition, e.g `Function<T, String>`.

I have played around with a simple draft implementation here (https://github.com/valid4j/descriptive-predicates) but it's obviously more of a proof of concept, than something that could become a pull request into hamcrest. WDYT?

**Comment by sf105** [comment]
Thanks for contributing. Java 8 is likely to bring such a shift that we ought to have a new version of Hamcrest. There have been several attempts, none quite with enough traction. Yours looks like the sort of thing we should be thinking of. As you've noticed, the critical point is getting the descriptions right, which is why it has to be more than just a single boolean function.
