### ISSUE TITLE
Java 9 Quick Win Pre Modules - Backport to 1.3.1?

### ISSUE THREAD

**Issue by nhojpatrick** [hamcrest/JavaHamcrest#187]
Lots of people might still be using hamcrest 1.3, or other frameworks might not wanting to be instantly upgrade to Java 9 modules.

What is the developer views regarding doing a 1.3.1 and adding "Automatic-Module-Name" to aid people left behind?

**Comment by noopur2507** [comment]
Eclipse Java Development Tools (JDT) is using org.hamcrest.core 1.3.0 while running JUnit 4 tests.  Since it does not have Automatic-Module-Name set in its manifest, it is currently not possible to use the hamcrest.core JAR on the modulepath in a Java 9 project. 

Can we have a new version of hamcrest.core as suggested in this bug report with Automatic-Module-Name?

**Comment by namannigam** [comment]
Not just this, I would say `hamcrest` would have to look into the [“Split Packages” Dependencies](https://stackoverflow.com/questions/53245628/jdk9-automatic-modules-and-split-packages-dependencies) as well.

**Comment by tumbarumba** [comment]
Now that Hamcrest 2.1 is out (#224), does this solve this problem?
